baseURL = 'https://fangr.cc/'
# [en, zh-cn, fr, pl, ...] determines default content language
# [en, zh-cn, fr, pl, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"

# 主题
theme = "uBlogger"
themeDir = "themes/uBlogger"
title = '$HOME - 给岁月以文明'

# 是否使用 robots.txt
enableRobotsTXT = true
# 是否使用 emoji 代码
enableEmoji = true
[languages]
  [languages.zh-cn]
    weight = 1
    # language code
    languageCode = "zh-cn"
    # language name
    languageName = "Chinese"
    # whether to include Chinese/Japanese/Korean
    hasCJKLanguage = true
    # default amount of posts in each pages
    paginate = 12
    # copyright description used only for seo schema
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    # Menu config
    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        identifier = "posts"
        # you can add extra information before the name (HTML format is supported), such as icons
        pre = ""
        # you can add extra information after the name (HTML format is supported), such as icons
        post = ""
        name = "Posts"
        url = "/posts/"
        # title will be shown when you hover on this menu link.
        title = ""
        weight = 1
      [[languages.zh-cn.menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.zh-cn.menu.main]]
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
        weight = 3
      [[languages.zh-cn.menu.main]]
        identifier = "about"
        pre = ""
        post = ""
        name = "About"
        url = "/about/"
        title = ""
        weight = 4
      [[languages.zh-cn.menu.main]]
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw'></i>"
        post = ""
        name = ""
        url = "https://github.com/upagge/ublogger"
        title = "GitHub"
        weight = 5
    [languages.zh-cn.params]
      # site description
      description = "About uBlogger Theme"
      # site keywords
      keywords = ["Theme", "Hugo"]
      # App icon config
      [languages.zh-cn.params.app]
        # optional site title override for the app when added to an iOS home screen or Android launcher
        title = "uBlogger"
        # whether to omit favicon resource links
        noFavicon = false
        # modern SVG favicon to use in place of older style .png and .ico files
        svgFavicon = ""
        # Android browser theme color
        themeColor = "#ffffff"
        # Safari mask icon color
        iconColor = "#5bbad5"
        # Windows v8-10 tile color
        tileColor = "#da532c"
      # Search config
      [languages.zh-cn.params.search]
        enable = true
        # type of search engine ("lunr", "algolia")
        type = "algolia"
        # max index length of the chunked content
        contentLength = 4000
        # placeholder of the search bar
        placeholder = ""
        # max number of results length
        maxResultLength = 10
        # snippet length of the result
        snippetLength = 30
        # HTML tag name of the highlight part in results
        highlightTag = "em"
        # whether to use the absolute URL based on the baseURL in search index
        absoluteURL = false
        [languages.zh-cn.params.search.algolia]
          index = "ryder_blog"
          appID = "KNWHHR2LLW"
          searchKey = "99980e3c2014fb8c463a83c546a3f4a6"
      # Home page config
      [languages.zh-cn.params.home]
        # amount of RSS pages
        rss = 10
        # Home page profile
        [languages.zh-cn.params.home.profile]
          enable = true
          # Gravatar Email for preferred avatar in home page
          gravatarEmail = ""
          # URL of avatar shown in home page
          avatarURL = "/avatar.png"
          # title shown in home page (HTML format is supported)
          title = "Ryder's Cube"
          # subtitle shown in home page (HTML format is supported)
          subtitle = "A Clean, Elegant but Advanced Hugo Theme"
          # whether to show social links
          social = true
          # disclaimer (HTML format is supported)
          disclaimer = ""
        # Home page posts
        [languages.zh-cn.params.home.posts]
          enable = true
          # special amount of posts in each home posts page
          paginate = 6
      # Social config in home page
      [languages.zh-cn.params.social]
        GitHub = "ryderfang"
        Twitter = "ryderfang"
        Email = "fray9166@gmail.com"
        RSS = true

[params]
    # uBlogger theme version
    version = "2.0.X"
    # site default theme ("light", "dark", "auto")
    defaultTheme = "auto"
    # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ("sha256", "sha384", "sha512", "md5")
    fingerprint = ""
    # 日期格式
    dateFormat = "2006-01-02"
    # 网站图片, 用于 Open Graph 和 Twitter Cards
    images = ["/logo.png"]

    # 页面头部导航栏配置
    [params.header]
        # 桌面端导航栏模式 ("fixed", "normal", "auto")
        desktopMode = "fixed"
        # 移动端导航栏模式 ("fixed", "normal", "auto")
        mobileMode = "auto"
        # 页面头部导航栏标题配置
        [params.header.title]
            # LOGO 的 URL
            logo = "/logo.jpg"
            # 标题名称
            name = "光锥之内皆是命运"
            # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
            pre = "<i class='fas fa-pencil-alt fa-fw'></i>"
            # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
            post = ""

    # 页面底部信息配置
    [params.footer]
        enable = true
        # 自定义内容 (支持 HTML 格式)
        custom = '© 2021 Ryder Fang · &lt;/&gt; Powered by <a href="https://gohugo.io/" target="_blank"><u><strong>Hugo</strong></u></a> and <a href="https://github.com/uPagge/uBlogger" target="_blank"><u><strong>uBlogger</strong></u></a>'
        # 是否显示 Hugo 和主题信息
        hugo = false
        # 是否显示版权信息
        copyright = false
        # 是否显示作者
        author = false
        # 网站创立年份
        since = 2016
        # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
        icp = "沪备"
        # 许可协议信息 (支持 HTML 格式)
        license= '<a href="https://en.wikipedia.org/wiki/Unlicense" target="_blank"><u>Unlicense</u></a>'
    
    # Section (所有文章) 页面配置
    [params.section]
        # section 页面每页显示文章数量
        paginate = 10
        # 日期格式 (月和日)
        dateFormat = "01-02"
        # RSS 文章数目
        rss = 10
    
    # List (目录或标签) 页面配置
    [params.list]
        # list 页面每页显示文章数量
        paginate = 20
        # 日期格式 (月和日)
        dateFormat = "01-02"
        # RSS 文章数目
        rss = 10

    # 评论系统设置
    [params.comment]
        enable = true
        # Utterances comment 评论系统设置 (https://utteranc.es/)
        [params.comment.utterances]
            enable = true
            # owner/repo
            repo = "ryderfang/ryderfang.github.io"
            issueTerm = "pathname"
            label = "Utterances"
            lightTheme = "github-light"
            darkTheme = "github-dark"

    # 文章页面配置
    [params.page]
        # 是否在主页隐藏一篇文章
        hiddenFromHomePage = false
        # 是否在搜索结果中隐藏一篇文章
        hiddenFromSearch = false
        # 是否使用 twemoji
        twemoji = false
        # 是否使用 ruby 扩展语法
        ruby = true
        # 是否使用 fraction 扩展语法
        fraction = true
        # 是否使用 fontawesome 扩展语法
        fontawesome = true
        # 是否显示原始 Markdown 文档内容的链接
        linkToMarkdown = true
        # 是否在 RSS 中显示全文内容
        rssFullText = false
        # 目录配置
        [params.page.toc]
            # 是否使用目录
            enable = true
            # 是否保持使用文章前面的静态目录
            keepStatic = false
            # 是否使侧边目录自动折叠展开
            auto = true
        # 代码配置
        [params.page.code]
            # 是否显示代码块的复制按钮
            copy = true
            # 默认展开显示的代码行数
            maxShownLines = 10
        # KaTeX 数学公式配置 (KaTeX https://katex.org/)
        [params.page.math]
            enable = false
            # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
            blockLeftDelimiter = ""
            blockRightDelimiter = ""
            # 默认行内定界符是 $ ... $ 和 \\( ... \\)
            inlineLeftDelimiter = ""
            inlineRightDelimiter = ""
            # KaTeX 插件 copy_tex
            copyTex = true
            # KaTeX 插件 mhchem
            mhchem = true
        # Mapbox GL JS 配置 (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
        [params.page.mapbox]
            # Mapbox GL JS 的 access token
            accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
            # 浅色主题的地图样式
            lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
            # 深色主题的地图样式
            darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
            # 是否添加 NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
            navigation = true
            # 是否添加 GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
            geolocate = true
            # 是否添加 ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
            scale = true
            # 是否添加 FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
            fullscreen = true
        # 文章页面的分享信息设置
        [params.page.share]
            enable = true
            Twitter = true
            Facebook = true
            Weibo = true
        # 第三方库配置
        [params.page.library]
        [params.page.library.css]
            # someCSS = "some.css"
            # located in "assets/" 位于 "assets/"
            # Or 或者
            # someCSS = "https://cdn.example.com/some.css"
        [params.page.library.js]
            # someJavascript = "some.js"
            # located in "assets/" 位于 "assets/"
            # Or 或者
            # someJavascript = "https://cdn.example.com/some.js"
        # 页面 SEO 配置
        [params.page.seo]
        # image URL
        # 图片 URL
        images = []
        # Publisher info
        # 出版者信息
        [params.page.seo.publisher]
            name = ""
            logoUrl = ""

# Hugo 解析文档的配置
[markup]
    # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = true
        noClasses = false
    # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.renderer]
            # 是否在文档中直接使用 HTML 标签
            unsafe = true
    # 目录设置
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6

# 作者配置
[author]
    name = "ryderfang"

# 网站地图配置
[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5

# Permalinks 配置 (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
    # posts = ":year/:month/:filename"
    posts = ":filename"

# 隐私信息配置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
    # privacy of the Google Analytics (replaced by params.analytics.google)
    # Google Analytics 相关隐私 (被 params.analytics.google 替代)
    [privacy.googleAnalytics]
        # ...
    [privacy.twitter]
        enableDNT = true
    [privacy.youtube]
        privacyEnhanced = true

# 用于输出 Markdown 格式文档的设置
[mediaTypes]
    [mediaTypes."text/plain"]
        suffixes = ["md"]

# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
    mediaType = "text/plain"
    isPlainText = true
    isHTML = false

# 用于 Hugo 输出文档的设置
[outputs]
    home = ["HTML", "RSS", "JSON"]
    page = ["HTML", "MarkDown"]
    section = ["HTML", "RSS"]
    taxonomy = ["HTML", "RSS"]
    taxonomyTerm = ["HTML"]